### ISSUE TITLE
[TRACKING ISSUE] Add Server-Side and Client-Side Notifications

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Ringer-Client-Desktop#147]
### Description
Add a feature where when Ringer is open and in use, if the user receives a message from someone that is not themselves and they are not focused in the window, Ringer will sent them a notification to their desktop. When Ringer is running in the background and there is no window open, Ringer will instead connect to a websocket notifications service in charge of sending notifications to the desktop when there are no windows open and Ringer is running in the background.

### Tasks
- [ ] Add Client-Side Notifications
- [ ] Create Server-Side Websocket Notifications Service
- [ ] Add Client Support For Websocket Notifications Service
