### ISSUE TITLE
Add "New Conversation" Support to Ringer

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Ringer-Client-Desktop#2]
Add the ability to send and receive/accept friend requests and have their conversation appear in the sidebar.

**Tasks**
- [x] Add the Ability to send friend requests
- [x] Add the ability to accept friend requests
- [ ] Add the ability to remove friend requests
- [x] Have current friends show up in the friends sidebar
