### ISSUE TITLE
Move Get Username and Get Token tools.

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Ringer-Client-Desktop#30]
**Description:**
Move the Get Username and Get Token tools into one utility called Cookie Manager. Then move this utility from the main page folder into the utils folder. 

**Tasks:**
- [ ] Move two utilities into one Cookie management utility
- [ ] Move utility into the utils folder for organization
- [ ] Update imports and references to use the new utility
