### ISSUE TITLE
Add "Forget Password" Ability

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Ringer-Client-Desktop#4]
Add "Forget Password" page to the client and add functionality to the server. 

### Tasks
- [x] Add "Forget Password" page
- [x] Make "Forgot Password" link on the login page navigate to "Forget Password" page
- [ ] Lif-Platforms/Lif-Auth-Server#9
- [ ] Add "Forget Password" functionality to page

**Comment by Superior126** [comment]
### NOTICE
This page will be removed as account recovery will be done through My Lif.
