### ISSUE TITLE
Add Stay Logged In Support

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Ringer-Client-Desktop#7]
**Description:**
Add a feature where the user does not need to be presented with the login screen after each new session. 

**Tasks**

- [x] Add a system on the server for tokens to remain the same between logins
- [x] Add a token check system to the server
- [x] Make the client check the token (if present) before redirecting to the login page
- [x] Make a system to redirect straight to the main page if the token is good

**Comment by Superior126** [comment]
**Update 1**
A system is in development that automatically saves the browser cookies into local storage before closing. Then when the app starts up, any data from local storage will be loaded into the browser cookies.
